Plano de testes Via_Cep_API
alcool70/pos-arquitetura-rest pull request #2
Opened 2020-11-29 20:31 UTC by victordemetrio

Grupo de usuários com Número de usuário: 100 - 500 - 1000 - 5000

- Site: https://viacep.com.br/
- Ação a ser tomada pelo testador: Continuar.
- Tempo de inicialização: 1 segundo
- Contador de interação: 4

2020-12-03 23:27 UTC, DsMenezes commented
Olá, vi que foi sugerido uma ação a ser tomada pelo testador, poderia ser mais específico?

2020-12-04 11:29 UTC, rustnnes commented
@victordemetrio @Deamgaudencioramos 
Ontem, avaliando os PRs do JMeter, vi a possibilidade de mesclar os 4 arquivos de cada PR em um só.
Abram o primeiro arquivo e depois no menu "Arquivo", escolham a opção "Mesclar", você pode selecionar outro arquivo.
E então, o JMeter mescla o Grupo de usuários de um arquivo com o outro...
Isso possibilita entregar um arquivo só por branch, ok? 😉

2020-12-04 11:32 UTC, rustnnes requested changes
Vide https://github.com/alcool70/pos-arquitetura-rest/pull/2#issuecomment-738733398

2020-12-04 11:32 UTC, rustnnes commented on Plano de Teste Consulta API Via Cep/Plano de Teste Consulta API Via Cep (1000).jmx
> +<?xml version="1.0" encoding="UTF-8"?>
Mesclar ao primeiro arquivo
Vide https://github.com/alcool70/pos-arquitetura-rest/pull/2#issuecomment-738733398

2020-12-04 11:32 UTC, rustnnes commented on Plano de Teste Consulta API Via Cep/Plano de Teste Consulta API Via Cep (500).jmx
> +<?xml version="1.0" encoding="UTF-8"?>
Mesclar ao primeiro arquivo 
Vide https://github.com/alcool70/pos-arquitetura-rest/pull/2#issuecomment-738733398

2020-12-04 11:32 UTC, rustnnes commented on Plano de Teste Consulta API Via Cep/Plano de Teste Consulta API Via Cep (5000).jmx
> +<?xml version="1.0" encoding="UTF-8"?>
Mesclar ao primeiro arquivo
Vide https://github.com/alcool70/pos-arquitetura-rest/pull/2#issuecomment-738733398

2020-12-05 19:18 UTC, merged