Plano de teste api iqris.in
alcool70/pos-arquitetura-rest pull request #4
Opened 2020-11-30 14:45 UTC by Deamgaudencioramos

Site: https://reqres.in/
Ação a ser tomada pelo testador: Continuar.
Thread Group: 500 - 5000 100-1000
Tempo de inicialização: 1 segundo
Contador de interação: 3

2020-12-03 23:26 UTC, DsMenezes commented
Olá, vi que foi sugerido uma ação a ser tomada pelo testador, poderia ser mais específico?

2020-12-04 11:37 UTC, rustnnes requested changes
@victordemetrio @Deamgaudencioramos
Ontem, avaliando os PRs do JMeter, vi a possibilidade de mesclar os 4 arquivos de cada PR em um só.
Abram o primeiro arquivo e depois no menu "Arquivo", escolham a opção "Mesclar", você pode selecionar outro arquivo.
E então, o JMeter mescla o Grupo de usuários de um arquivo com o outro...
Isso possibilita entregar um arquivo só por branch, ok? 😉

2020-12-04 11:37 UTC, rustnnes commented on Plano de teste inqris_API -/teste(1000).jmx
> +<?xml version="1.0" encoding="UTF-8"?>
Mesclar ao primeiro arquivo

2020-12-04 11:37 UTC, rustnnes commented on Plano de teste inqris_API -/teste(500).jmx
> +<?xml version="1.0" encoding="UTF-8"?>
Mesclar ao primeiro arquivo

2020-12-04 11:37 UTC, rustnnes commented on Plano de teste inqris_API -/teste(5000).jmx
> +<?xml version="1.0" encoding="UTF-8"?>
Mesclar ao primeiro arquivo

2020-12-04 12:30 UTC, Deamgaudencioramos commented
> Olá, vi que foi sugerido uma ação a ser tomada pelo testador, poderia ser mais específico?

Determina o que acontece se ocorre algum erro nas requisições, no caso esta marcado para ele ignorar o erro e continuar até finalizar todo o teste

2020-12-05 12:25 UTC, merged